"""Python port of the kernel mapper v0 (mapper/src: tokenize.ts,
lemmatize.ts, lexicon.ts, mapper.ts, policy.ts) for the E1 data pipeline
(beads kernel-of-truth-bk0, kernel-of-truth-9qm).

DATA comes exclusively from the committed artifact
poc/e1/inputs/mapper-lexicon.json (generated by harness/lexiconArtifact.ts,
which verifies its transcribed tables behaviourally against the live mapper
and stamps mapper-source sha-256s). ALGORITHMS are line-for-line ports of the
TS modules. Correctness is gated, not assumed: build_data.py refuses to emit
shards unless this port reproduces the mapper's canonical decision-stream
sha-256 over the parity fixture (poc/e1/inputs/mapper-parity-fixture.json)
— lemma tables, sample annotations, and (when the corpus file matches the
fixture's sha) the full-slice stream hash.

AMENDMENT A1 (docs/poc-design.md Phase M, signed 2026-07-07): the lexicon
artifact embeds the adopted mapper policy (`a1-hybrid`, sha e13dc838…):
sense-priority tiers resolving EXACTLY declared ambiguous decision sets
({inside, near, broken}) to a declared winner — a port of mapper/src/policy.ts
compilePriorityIndex + the tier branch of decideFromTargets. Exact-set keying
fails closed: any undeclared multi-target set still abstains. The policy's
excludeConcepts ({kind, lost}) do NOT change mapper decisions; they shrink
the declared evaluated concept set downstream (build_data.py).
"""

import json
import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

WORD_RE = re.compile(r"[A-Za-z]+(?:['’][A-Za-z]+)*")
NONSPACE_RE = re.compile(r"[^\sA-Za-z]+")
SPACE_RE = re.compile(r"\s")
ES_RE = re.compile(r"(?:s|x|z|ch|sh|o)es$")

VOWELS = frozenset("aeiou")


@dataclass
class Token:
    surface: str
    norm: str  # '' for non-words
    start: int
    end: int
    is_word: bool
    is_expansion: bool


@dataclass
class Annotated:
    surface: str
    norm: str
    lemma: str
    start: int
    end: int
    is_word: bool
    is_expansion: bool
    kind: str  # concept | prime | abstain | none
    target: str  # conceptId | prime name | '' ; abstain: sorted keys joined ','
    phrase_len: int
    phrase_pos: int


class KernelMapper:
    def __init__(self, artifact: dict):
        if artifact.get("artifact") != "e1-mapper-lexicon":
            raise ValueError("ERR_ARTIFACT: not an e1-mapper-lexicon artifact")
        self.provenance = artifact["provenance"]

        # ---- policy.ts: compilePriorityIndex (Amendment A1) ----------------
        # `policy` is absent from pre-A1 artifacts; then behaviour is the
        # original abstain-and-record mapper, bit-exact.
        self.policy: Optional[dict] = artifact.get("policy")
        self.priority_index: Dict[str, Tuple[str, str]] = {}
        if self.policy is not None:
            name = self.policy.get("name", "?")
            for rule in self.policy.get("priorityTiers", []):
                sorted_set = sorted(rule["decisionSet"])
                if len(sorted_set) < 2:
                    raise ValueError(
                        f"ERR_POLICY_DEGENERATE_SET: [{'|'.join(sorted_set)}] in {name}")
                if rule["winner"] not in sorted_set:
                    raise ValueError(
                        f"ERR_POLICY_WINNER_NOT_IN_SET: {rule['winner']} not in "
                        f"[{'|'.join(sorted_set)}] ({name})")
                key = "|".join(sorted_set)
                if key in self.priority_index:
                    raise ValueError(f"ERR_POLICY_DUPLICATE_SET: [{key}] declared twice in {name}")
                w = rule["winner"]
                self.priority_index[key] = (
                    ("prime", w[len("prime:"):]) if w.startswith("prime:") else ("concept", w))

        lem = artifact["lemmatizer"]
        self.irregular: Dict[str, str] = dict(lem["irregular"])
        self.no_strip = frozenset(lem["noStrip"])
        tok = artifact["tokenizer"]
        self.special: Dict[str, List[str]] = {k: list(v) for k, v in tok["special"].items()}
        self.pronoun_s_is = frozenset(tok["pronounSIs"])

        # lexicon indexes (mirror of lexicon.ts buildLexicon output shape);
        # artifact entries preserve buildLexicon order, so stable sorting by
        # descending phrase length reproduces the TS multiword ordering.
        self.multiword: Dict[str, List[Tuple[List[str], str, str]]] = {}
        self.single: Dict[str, List[Tuple[str, str]]] = {}
        self.max_phrase_len = 1
        for e in artifact["entries"]:
            phrase = list(e["phrase"])
            t = e["target"]
            kind = t["kind"]
            key = t["prime"] if kind == "prime" else t["conceptId"]
            if len(phrase) > 1:
                self.multiword.setdefault(phrase[0], []).append((phrase, kind, key))
                self.max_phrase_len = max(self.max_phrase_len, len(phrase))
            else:
                self.single.setdefault(phrase[0], []).append((kind, key))
        for lst in self.multiword.values():
            lst.sort(key=lambda x: -len(x[0]))  # stable, like the TS sort

    # ---- tokenize.ts ------------------------------------------------------

    def _expand_word(self, lower: str) -> List[str]:
        special = self.special.get(lower)
        if special is not None:
            return special
        if lower.endswith("n't") and len(lower) > 3:
            return [lower[:-3], "not"]
        if lower.endswith("'ll") and len(lower) > 3:
            return [lower[:-3], "will"]
        if lower.endswith("'re") and len(lower) > 3:
            return [lower[:-3], "are"]
        if lower.endswith("'ve") and len(lower) > 3:
            return [lower[:-3], "have"]
        if lower.endswith("'m") and len(lower) > 2:
            return [lower[:-2], "am"]
        if lower.endswith("'d") and len(lower) > 2:
            return [lower[:-2], "would"]
        if lower.endswith("'s") and len(lower) > 2:
            base = lower[:-2]
            if base in self.pronoun_s_is:
                return [base, "is"]
            return [base]  # possessive: drop the clitic
        if lower.endswith("'") and len(lower) > 1:
            return [lower[:-1]]
        return [lower]

    def tokenize(self, text: str) -> List[Token]:
        out: List[Token] = []
        i, n = 0, len(text)
        while i < n:
            if SPACE_RE.match(text, i):
                i += 1
                continue
            wm = WORD_RE.match(text, i)
            if wm is not None:
                surface = wm.group(0)
                lower = surface.lower().replace("’", "'")
                parts = self._expand_word(lower)
                for p, part in enumerate(parts):
                    out.append(Token(surface, part, i, i + len(surface), True, p > 0))
                i += len(surface)
                continue
            nm = NONSPACE_RE.match(text, i)
            if nm is not None:
                surface = nm.group(0)
                out.append(Token(surface, "", i, i + len(surface), False, False))
                i += len(surface)
                continue
            i += 1  # unreachable safety

        return out

    # ---- lemmatize.ts -----------------------------------------------------

    @staticmethod
    def _is_consonant(ch: str) -> bool:
        return len(ch) == 1 and "a" <= ch <= "z" and ch not in VOWELS

    def _stem_candidates(self, stem: str) -> List[str]:
        out: List[str] = []
        if len(stem) >= 2:
            out.append(stem)
        last = stem[-1] if stem else ""
        prev = stem[-2] if len(stem) >= 2 else ""
        if self._is_consonant(last) and len(stem) >= 2:
            out.append(stem + "e")
        if len(stem) >= 3 and last == prev and self._is_consonant(last) and last not in "lsfz":
            out.append(stem[:-1])
        return out

    def lemma_candidates(self, word: str) -> List[str]:
        out = [word]

        def push(w: str) -> None:
            if len(w) >= 2 and w not in out:
                out.append(w)

        irr = self.irregular.get(word)
        if irr is not None:
            push(irr)
        if word in self.no_strip or len(word) < 3:
            return out

        if word.endswith("ies") and len(word) > 4:
            push(word[:-3] + "y")
        elif word.endswith("es") and ES_RE.search(word):
            push(word[:-2])
            push(word[:-1])
        elif word.endswith("s") and not word.endswith("ss") and not word.endswith("us"):
            push(word[:-1])

        if word.endswith("ied") and len(word) > 4:
            push(word[:-3] + "y")
        elif word.endswith("ed") and len(word) > 3:
            for c in self._stem_candidates(word[:-2]):
                push(c)

        if word.endswith("ing") and len(word) > 4:
            for c in self._stem_candidates(word[:-3]):
                push(c)

        if word.endswith("iest") and len(word) > 5:
            push(word[:-4] + "y")
        elif word.endswith("est") and len(word) > 4:
            for c in self._stem_candidates(word[:-3]):
                push(c)
        if word.endswith("ier") and len(word) > 4:
            push(word[:-3] + "y")
        elif word.endswith("er") and len(word) > 3:
            for c in self._stem_candidates(word[:-2]):
                push(c)

        return out

    # ---- mapper.ts --------------------------------------------------------

    @staticmethod
    def _target_key(kind: str, key: str) -> str:
        return f"prime:{key}" if kind == "prime" else key

    def _decide(self, targets: List[Tuple[str, str]]) -> Tuple[str, str]:
        """targets: unique (kind, key) list -> (kind, canonical target string).

        Port of mapper.ts decideFromTargets: a multi-target set is resolved
        iff a policy tier declared EXACTLY this decision set (Amendment A1);
        every other multi-target set abstains, as always.
        """
        if not targets:
            return "none", ""
        if len(targets) == 1:
            kind, key = targets[0]
            return kind, key if kind == "concept" else key
        keys = sorted(KernelMapper._target_key(k, v) for k, v in targets)
        winner = self.priority_index.get("|".join(keys))
        if winner is not None:
            return winner
        return "abstain", ",".join(keys)

    @staticmethod
    def _unique(targets: List[Tuple[str, str]]) -> List[Tuple[str, str]]:
        seen = set()
        out = []
        for t in targets:
            k = KernelMapper._target_key(*t)
            if k in seen:
                continue
            seen.add(k)
            out.append(t)
        return out

    def map_tokens(self, tokens: List[Token]) -> List[Annotated]:
        out: List[Annotated] = []
        i = 0
        n = len(tokens)
        while i < n:
            tok = tokens[i]
            if not tok.is_word:
                out.append(Annotated(tok.surface, tok.norm, "", tok.start, tok.end,
                                     False, False, "none", "", 1, 0))
                i += 1
                continue

            # 1. multiword, longest-match-first
            heads = self.multiword.get(tok.norm)
            matched = False
            if heads is not None:
                best_len = 0
                best_targets: List[Tuple[str, str]] = []
                for phrase, kind, key in heads:
                    if best_len > 0 and len(phrase) < best_len:
                        break
                    ln = len(phrase)
                    if i + ln > n:
                        continue
                    ok = True
                    for k in range(1, ln):
                        t = tokens[i + k]
                        if not t.is_word or t.norm != phrase[k]:
                            ok = False
                            break
                    if ok:
                        best_len = ln
                        best_targets.append((kind, key))
                if best_len > 0:
                    kind, target = self._decide(self._unique(best_targets))
                    for k in range(best_len):
                        t = tokens[i + k]
                        out.append(Annotated(t.surface, t.norm, t.norm, t.start, t.end,
                                             True, t.is_expansion, kind, target, best_len, k))
                    i += best_len
                    matched = True
            if matched:
                continue

            # 2. single token over lemma candidates
            candidates = self.lemma_candidates(tok.norm)
            targets: List[Tuple[str, str]] = []
            lemma = candidates[0]
            lemma_fixed = False
            for cand in candidates:
                hits = self.single.get(cand)
                if hits is None:
                    continue
                if not lemma_fixed:
                    lemma = cand
                    lemma_fixed = True
                targets.extend(hits)
            kind, target = self._decide(self._unique(targets))
            out.append(Annotated(tok.surface, tok.norm, lemma, tok.start, tok.end,
                                 True, tok.is_expansion, kind, target, 1, 0))
            i += 1
        return out

    def map_text(self, text: str) -> List[Annotated]:
        return self.map_tokens(self.tokenize(text))


def decision_line(a: Annotated) -> str:
    """Canonical decision-stream line — MUST match harness/lexiconArtifact.ts
    decisionLine(): 'norm|kind|target|phraseLen|phrasePos'. Annotated.target
    stores the RAW prime name; the canonical line carries the 'prime:' key."""
    target = f"prime:{a.target}" if a.kind == "prime" else a.target
    return f"{a.norm}|{a.kind}|{target}|{a.phrase_len}|{a.phrase_pos}"


def load_mapper(artifact_path: str) -> KernelMapper:
    with open(artifact_path, "r", encoding="utf-8") as f:
        return KernelMapper(json.load(f))
