#!/usr/bin/env python3
"""build_clutrr_r3_corpus — FRESH held-out covered corpus data/nsk1-clutrr-r3 (runner role).

Implements the nsk1-r3 pre-freeze data build of docs/next/design/nsk1-r3-hardened.md
§6.2/§6.4 step 1 (ASM-2357) + registry/experiments/nsk1-r3.json n_planned.confirmatory_corpus:
the pinned-config covered pool is EXHAUSTED (data/nsk1-clutrr/manifest.json
counts.remainder_unused = 0, all 958 consumed by B'/B"/Stage-1), so a fresh,
never-contacted covered slice is REGENERATED with the pinned CLUTRR generator
(facebookresearch/clutrr @ d045fae2, the same commit pinned by the nsk1-clutrr
manifest) at NEW seed 20260720, filtered by the SAME S4 covered predicate as
poc/nsk1/build_clutrr_corpus.py (clean k=2 up-edge-only chains over {mother,
father}, gold in {grandmother, grandfather}, all facts in-context), deduped,
verified DISJOINT from every prior-contacted item, and split by seed 20260726
into two disjoint partitions A (primary cell (16,16)) and B (replication cell
(12,16)).

S2/S3/S4/S6 parsing, the covered predicate, and the S9 build assertions are
carried VERBATIM from poc/nsk1/build_clutrr_corpus.py (builder_sha256
b82993cec1322a0040ed00266a36f18a1d9b90b753e71e0826a038e46362db77); only the row
SOURCE changes (pinned generator output instead of the exhausted released CSVs)
plus the r3-specific disjointness + partition steps. Fail-closed: any failed
assertion ABORTS (RuntimeError); nothing is patched around.

DISCLOSED DEVIATION (D-1, requires designer adjudication BEFORE freeze): the
design stipulates the generator path "yields distributionally identical fresh
items". The released corpus was rendered from the AMT paraphrase templates
(cleaned_placeholders.zip, sha256 ed2264...24 pinned inside the generator's own
main.py). That artifact is NO LONGER OBTAINABLE: the canonical URL
cs.mcgill.ca/~ksinha4/data/cleaned_placeholders.zip 404s (redirects to
koustuvsinha.com, 404), no Wayback snapshot exists, and no public mirror was
found (GitHub code/path search, forks, PyPI, HuggingFace; checked 2026-07-14).
This build therefore runs the pinned generator's SYNTHETIC templating branch
(use_mturk_template=False, combination_length=1 — forced by the generator: the
synthetic branch raises NotImplementedError for combination_length > 1): story
STRUCTURE (chains, genders, proof_state, query) is generated by the identical
pinned code, but story SURFACES come from the generator's built-in per-relation
phrasings (clutrr/store/relations_store.yaml 'p' lists), not AMT paraphrases.
Item surfaces are therefore terser and less varied than B"'s. Freeze must not
proceed until the designer either accepts D-1 (amending ASM-2357's
"distributionally identical" wording to "structurally identical, surface-
deviating (synthetic templating), headroom-gated in-run") or supplies the AMT
templates.

Question path: ALL 958 prior covered items used the fallback question template
("How is [A] related to [B]?", released query order) because released
text_query was empty (prior manifest question_path). To keep the question
surface IDENTICAL to what B'/B"/Stage-1 measured, the fallback template is used
for every fresh item; the generator's synthetic text_query is preserved,
unused, in provenance.

Outputs data/nsk1-clutrr-r3/: items.jsonl (covered only, with partition A/B),
world.jsonl, lexicon.json, axioms/ (byte-copy of data/nsk1-eval/axioms/),
manifest.json, LICENSE-NOTICE. No controls / headroom files: r3's coin+role
controls are derangement-derived and the headroom gate scores the full fresh
set in-run (design §5.1/§6.1).

BUILD ONLY: writes data/nsk1-clutrr-r3/ and prints the §6.3 count gate. It
does NOT freeze, does NOT write any registry pin, does NOT touch git.

    PYTHONHASHSEED=0 <clutrr-gen-venv>/bin/python poc/nsk1/build_clutrr_r3_corpus.py

(PYTHONHASHSEED=0 is ENFORCED — str-keyed set/dict iteration inside the pinned
generator must not vary with hash salt; the build re-execs itself if unset.)
"""
import ast
import hashlib
import json
import os
import random
import re
import shutil
import subprocess
import sys

# ---- PYTHONHASHSEED enforcement (byte-reproducibility across processes) ----
if os.environ.get("PYTHONHASHSEED") != "0":
    env = dict(os.environ, PYTHONHASHSEED="0")
    os.execve(sys.executable, [sys.executable] + sys.argv, env)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "axiom"))
from kot_axiom import Engine  # noqa: E402

GEN_SEED = 20260720    # design §6.2 (ASM-2357): NEW generation seed
SPLIT_SEED = 20260726  # design §6.2: disjoint A/B partition split seed
N_TARGET = 300         # design §6.3 (ASM-2359): target n per cell
N_FLOOR = 175          # design §6.3: non-freeze floor per cell
# Builder constant: with --equal the 4 covered f_combs are ~4/62 of k=2 rows
# (measured 6.4% on the released pool); 12000 rows -> ~770 covered candidates,
# comfortably above the 600 needed for the full-power branch.
N_GEN_ROWS = 12000
GENERATOR_COMMIT = "d045fae289d3746503677ceed7631c999202501e"  # nsk1-r3 record pin

GEN_DIR = os.path.join(ROOT, "data", "clutrr-cache", "clutrr")
RELSTORE = os.path.join(GEN_DIR, "clutrr", "store", "relations_store.yaml")
SRC_AXIOMS = os.path.join(ROOT, "data", "nsk1-eval", "axioms")
PRIOR = os.path.join(ROOT, "data", "nsk1-clutrr")
OUT = os.path.join(ROOT, "data", "nsk1-clutrr-r3")

# Kernel concept URNs — the SAME minted concepts data/nsk1-eval + nsk1-clutrr
# use (prior builder S7; CLUTRR bytes are eval-side only, S11).
REL_MOTHER = "urn:kot:bciqdkz3mwjzgrbptwmryvvp5nwg7fuu6crj5e63i5y5cdkq4v2r6mua"
REL_FATHER = "urn:kot:bciqgs7ze663hfdaq7be4jnuuue5nywum6qhdciqgq7greuyyobz6jqi"
CLS_MAN = "urn:kot:bciqkttqo6lnzwz7u72dbbpteqryr76cdyj7glivilcqribbggeqofsy"
CLS_WOMAN = "urn:kot:bciqbz6th7ul3gmk5bhtovyi2yifyv7twotuvwjcebgetthcs532sgoq"
REL_OF = {"mother": REL_MOTHER, "father": REL_FATHER}
REL_SURFACE = {REL_MOTHER: "mother", REL_FATHER: "father"}

UP = {"mother", "father"}
GRAND = {"grandmother", "grandfather"}
GRAND_OF = {"father": "grandfather", "mother": "grandmother"}
GENDER_OF_EDGE = {"father": "male", "mother": "female"}

REQUIRED_COLS = ["id", "story", "query", "target", "clean_story", "proof_state",
                 "f_comb", "story_edges", "edge_types", "query_edge", "genders",
                 "task_name", "task_split"]


def sha256_bytes(b):
    return hashlib.sha256(b).hexdigest()


def slug(name):
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s or "x"


# ---- S2 parse helpers, VERBATIM from poc/nsk1/build_clutrr_corpus.py ----
def parse_row(r):
    try:
        se = ast.literal_eval(r["story_edges"])
        et = ast.literal_eval(r["edge_types"])
        qe = ast.literal_eval(r["query_edge"])
        ps = ast.literal_eval(r["proof_state"])
        q = ast.literal_eval(r["query"])
    except Exception:
        return None
    if not (isinstance(se, list) and isinstance(et, list) and isinstance(qe, tuple)
            and isinstance(ps, list) and isinstance(q, tuple)):
        return None
    return se, et, qe, ps, q


def proof_support(ps):
    try:
        key = list(ps[0].keys())[0]
        return ps[0][key]
    except Exception:
        return None


def endpoints_C1(se):
    """C1 edge convention: edge (a,b) means b is the (mother/father) of a."""
    parent = {a: b for (a, b) in se}
    dom, rng = set(parent), set(parent.values())
    base = list(dom - rng)
    top = list(rng - dom)
    if len(base) != 1 or len(top) != 1:
        return None, None
    return base[0], top[0]


def edge_by_child_C1(se, et):
    return {a: (b, t) for (a, b), t in zip(se, et)}


def parse_genders(s):
    out = {}
    for part in s.split(","):
        if ":" in part:
            k, v = part.split(":", 1)
            out[k.strip()] = v.strip()
    return out


# ---- S3 orientation determination, VERBATIM from build_clutrr_corpus.py ----
def orientation_scores(rows2):
    combos = {("C1", "Q1"): [0, 0], ("C1", "Q2"): [0, 0],
              ("C2", "Q1"): [0, 0], ("C2", "Q2"): [0, 0]}
    gmis = 0
    for se, et, qe, q, target, genders in rows2:
        for EC in ("C1", "C2"):
            if EC == "C1":
                parent = {a: (b, t) for (a, b), t in zip(se, et)}
            else:
                parent = {b: (a, t) for (a, b), t in zip(se, et)}
            dom, rng = set(parent), set(p for p, _ in parent.values())
            base = list(dom - rng)
            top = list(rng - dom)
            if len(base) != 1 or len(top) != 1:
                continue
            base, top = base[0], top[0]
            p1, t1 = parent[base]
            t2 = parent[p1][1] if p1 in parent else None
            pred = GRAND_OF.get(t2)
            for QC in ("Q1", "Q2"):
                gc, gp = (qe[0], qe[1]) if QC == "Q1" else (qe[1], qe[0])
                ok = (pred == target) and (base == gc) and (top == gp)
                combos[(EC, QC)][0] += 1 if ok else 0
                combos[(EC, QC)][1] += 1
        base, top = endpoints_C1(se)
        if base is not None:
            ebc = edge_by_child_C1(se, et)
            bridge, _t1 = ebc[base]
            t2 = ebc[bridge][1]
            idx2name = {qe[0]: q[0], qe[1]: q[1]}
            topname = idx2name.get(top)
            if topname in genders and genders[topname] != GENDER_OF_EDGE[t2]:
                gmis += 1
    scores = {"%s/%s" % k: (v[0] / v[1] if v[1] else 0.0) for k, v in combos.items()}
    counts = {"%s/%s" % k: v for k, v in combos.items()}
    return scores, counts, gmis


# ------------------------------------------------------------------ generator
def verify_generator_pin():
    got = subprocess.check_output(
        ["git", "-C", GEN_DIR, "rev-parse", "HEAD"]).decode().strip()
    if got != GENERATOR_COMMIT:
        raise RuntimeError("ERR_GENERATOR_PIN: HEAD %s != pinned %s (run "
                           "data/clutrr-cache/fetch.sh)" % (got, GENERATOR_COMMIT))
    return got


def run_pinned_generator():
    """Seeded invocation of the pinned generator's own generate_rows (task 1.2,
    clean, k=2) under the released clean config's graph parameters (max_levels 3,
    min_child 4, max_child 4, p_marry 1.0, --equal; data_089907f8 config.json)
    with the D-1 synthetic-templating deviation (module docstring)."""
    import numpy as np
    sys.path.insert(0, GEN_DIR)
    from clutrr.args import get_args           # pinned d045fae2
    from clutrr.store.store import Store       # pinned d045fae2
    from clutrr.generator import generate_rows  # pinned d045fae2

    random.seed(GEN_SEED)
    np.random.seed(GEN_SEED)

    # stub template file: generate_rows unconditionally loads
    # <template_file>.train/.test.json before the synthetic branch replaces
    # both variables; content is never used with use_mturk_template=False.
    stub = os.path.join(OUT, "_template_stub")
    os.makedirs(OUT, exist_ok=True)
    for sfx in (".train.json", ".test.json"):
        with open(stub + sfx, "w") as f:
            json.dump({}, f)

    args = get_args(command="--train_tasks 1.2 --test_tasks 1.2 --equal --question 0")
    args.template_file = stub
    args.use_mturk_template = False   # D-1: AMT templates unobtainable
    args.combination_length = 1       # forced by the synthetic branch
    args.noise_support = args.noise_irrelevant = False
    args.noise_disconnected = args.noise_attributes = False
    args.memory = 0                   # mirrors main._init_vars + released config
    args.relation_length = 2
    args.num_rows = N_GEN_ROWS
    args.data_type = "train"
    store = Store(args)
    cols, rows, _puzzles, _trp, _tep = generate_rows(
        args, store, "task_1.2", split=0.8, prev_patterns={})
    for sfx in (".train.json", ".test.json"):
        os.remove(stub + sfx)
    invocation = {
        "entry": "clutrr.generator.generate_rows(args, store, 'task_1.2', split=0.8)",
        "argv_equivalent": "--train_tasks 1.2 --test_tasks 1.2 --equal --question 0",
        "overrides": {"use_mturk_template": False, "combination_length": 1,
                      "template_file": "(empty stub, unused)", "memory": 0,
                      "noise_*": False, "relation_length": 2,
                      "num_rows": N_GEN_ROWS, "data_type": "train", "split": 0.8},
        "graph_params": {"max_levels": 3, "min_child": 4, "max_child": 4,
                         "p_marry": 1.0, "boundary": True, "equal": True},
        "seeding": {"random.seed": GEN_SEED, "numpy.random.seed": GEN_SEED,
                    "PYTHONHASHSEED": "0"},
    }
    return cols, rows, invocation


def rows_to_recs(cols, rows):
    """Serialize in-memory generator rows through the released-CSV string forms
    so S2 parsing (parse_row / ast.literal_eval) applies VERBATIM. csv_row_id is
    the deterministic generation index (the generator's uuid4 pid is process-
    random and would break byte-reproducibility; recorded decision)."""
    out = []
    for i, row in enumerate(rows):
        d = dict(zip(cols, row))
        out.append({
            "id": "genrow-%06d" % i,
            "story": d["story"],
            "query": str(d["query"]),
            "text_query": str(d["text_query"]),
            "target": d["target"],
            "clean_story": d["clean_story"],
            "proof_state": str(d["proof_state"]),
            "f_comb": d["f_comb"],
            "task_name": d["task_name"],
            "story_edges": str(d["story_edges"]),
            "edge_types": str(d["edge_types"]),
            "query_edge": str(d["query_edge"]),
            "genders": d["genders"],
            "task_split": d["task_split"],
        })
    return out


def main():
    commit = verify_generator_pin()
    relstore_bytes = open(RELSTORE, "rb").read()
    rel_words = sorted(set(re.findall(r"rel:\s*([a-zA-Z-]+)", relstore_bytes.decode())))

    # dependency provenance (build environment record)
    import numpy
    import pandas
    import yaml as _yaml
    import networkx
    dep_versions = {"python": sys.version.split()[0], "numpy": numpy.__version__,
                    "pandas": pandas.__version__, "PyYAML": _yaml.__version__,
                    "networkx": networkx.__version__}

    print("[r3] generating %d fresh task-1.2 rows with pinned generator %s ..."
          % (N_GEN_ROWS, commit[:12]))
    cols, raw_rows, invocation = run_pinned_generator()
    recs_all = rows_to_recs(cols, raw_rows)
    print("[r3] generated rows: %d" % len(recs_all))

    # ---- S2 parse + S4 covered filter (VERBATIM predicate, prior builder) ----
    rows2_for_s3 = []
    covered_cands = []
    drop_fcomb = drop_dup_in_item = drop_gender = drop_parse = 0
    for r in recs_all:
        if any(c not in r for c in REQUIRED_COLS):
            raise RuntimeError("ERR_MISSING_COLUMN in generated row %s" % r["id"])
        p = parse_row(r)
        if not p:
            drop_parse += 1
            continue
        se, et, qe, ps, q = p
        supp = proof_support(ps)
        two_edge = (len(se) == 2 and len(et) == 2 and supp is not None
                    and len(supp) == 2)
        if not two_edge:
            continue
        genders = parse_genders(r["genders"])
        if set(et) <= UP and r["target"] in GRAND:
            rows2_for_s3.append((se, et, qe, q, r["target"], genders))

        base, top = endpoints_C1(se)
        if base is None:
            continue
        ebc = edge_by_child_C1(se, et)
        if base not in ebc:
            continue
        bridge, t1 = ebc[base]
        if bridge not in ebc:
            continue
        gtop, t2 = ebc[bridge]
        if gtop != top:
            continue
        idx2name = {qe[0]: q[0], qe[1]: q[1]}
        base_name = idx2name.get(base)
        top_name = idx2name.get(top)
        if base_name is None or top_name is None:
            continue
        b0 = {supp[0][0], supp[0][2]}
        b1 = {supp[1][0], supp[1][2]}
        shared = list(b0 & b1)
        if len(shared) != 1:
            continue
        bridge_name = shared[0]
        ents3 = [base_name, bridge_name, top_name]

        rec = {"cfg": "generated-r3-seed%d" % GEN_SEED, "file": "task_1.2-synthetic",
               "ridx": int(r["id"].split("-")[1]), "id": r["id"],
               "story": r["story"], "target": r["target"],
               "f_comb": r["f_comb"], "task_name": r["task_name"],
               "task_split": r["task_split"], "genders_raw": r["genders"],
               "edge_types": et, "story_edges": se, "query_edge": qe,
               "proof_state": r["proof_state"], "query": q,
               "text_query": r.get("text_query", ""),
               "base": base_name, "bridge": bridge_name, "top": top_name,
               "t1": t1, "t2": t2, "genders": genders}

        # ---- S4: covered filter (VERBATIM) ----
        if set(et) <= UP and r["target"] in GRAND:
            if r["f_comb"] != "-".join(et):
                drop_fcomb += 1
                continue
            if set(qe) != {base, top}:
                continue
            if len(set(ents3)) != 3:
                drop_dup_in_item += 1
                continue
            ok = all(n in genders and genders[n] in ("male", "female")
                     for n in ents3)
            if ok and (genders[bridge_name] != GENDER_OF_EDGE[t1]
                       or genders[top_name] != GENDER_OF_EDGE[t2]):
                ok = False
            if not ok:
                drop_gender += 1
                continue
            covered_cands.append(rec)

    # ---- S3 orientation (self-verifying on the FRESH population) ----
    scores, counts, gmis = orientation_scores(rows2_for_s3)
    winners = [k for k, v in scores.items() if v >= 0.995]
    if winners != ["C1/Q1"]:
        raise RuntimeError("ERR_ORIENTATION_AMBIGUOUS: exactly one combo must reach "
                           ">=0.995 and it must be C1/Q1; got %s (scores=%s)"
                           % (winners, scores))

    # ---- S6 dedup by story bytes (generation order = deterministic) ----
    covered_cands.sort(key=lambda r: r["ridx"])
    seen, covered, dup_cov = set(), [], 0
    for rec in covered_cands:
        k = sha256_bytes(rec["story"].encode())
        if k in seen:
            dup_cov += 1
            continue
        seen.add(k)
        covered.append(rec)

    # ---- r3 DISJOINTNESS vs every prior-contacted item (design §6.2) ----
    prior_shas = set()
    for path, sf in (("data/nsk1-clutrr/items.jsonl", None),
                     ("data/nsk1-clutrr/headroom.jsonl", None)):
        for line in open(os.path.join(ROOT, path)):
            if not line.strip():
                continue
            it = json.loads(line)
            prior_shas.add(it["provenance"]["story_sha256"])
    if len(prior_shas) != 1058:  # 858 covered + 100 controls + 100 headroom
        raise RuntimeError("ERR_PRIOR_POOL: expected 1058 distinct prior story shas, "
                           "got %d" % len(prior_shas))
    fresh, overlap_dropped = [], 0
    for rec in covered:
        if sha256_bytes(rec["story"].encode()) in prior_shas:
            overlap_dropped += 1
            continue
        fresh.append(rec)
    pool = len(fresh)
    print("[r3] covered candidates=%d deduped=%d prior-overlap dropped=%d pool=%d"
          % (len(covered_cands), len(covered), overlap_dropped, pool))

    # ---- disjoint A/B partitions by SPLIT_SEED (design §6.2) ----
    n_cell = min(N_TARGET, pool // 2)
    rng = random.Random(SPLIT_SEED)
    idx = list(range(pool))
    rng.shuffle(idx)
    a_idx = sorted(idx[:n_cell])
    b_idx = sorted(idx[n_cell:2 * n_cell])
    assert not (set(a_idx) & set(b_idx)), "ABORT: A/B index overlap"
    part_a = [fresh[i] for i in a_idx]
    part_b = [fresh[i] for i in b_idx]

    # ------------------------------------------------------------------ emit
    world = []
    wid = [0]

    def w(rec, prov):
        wid[0] += 1
        rec["id"] = "w%06d" % wid[0]
        rec["schema"] = "kot-world/1"
        rec["provenance"] = prov
        world.append(rec)

    skipped_class_missing_gender = [0]

    def ent_urn(item_id, name):
        return "urn:kotw:v0:%s-%s" % (item_id, slug(name))

    def emit_covered(rec, item_id, partition):
        prov_src = "clutrr-generated %s %s row %s" % (rec["cfg"], rec["file"], rec["id"])
        prov = {"source": prov_src}
        lex = {}
        for name in (rec["base"], rec["bridge"], rec["top"]):
            urn = ent_urn(item_id, name)
            lex[urn] = name
            g = rec["genders"].get(name)
            if g in ("male", "female"):
                w({"kind": "class", "entity": urn,
                   "concept": CLS_MAN if g == "male" else CLS_WOMAN}, prov)
            else:
                skipped_class_missing_gender[0] += 1
        base_urn = ent_urn(item_id, rec["base"])
        bridge_urn = ent_urn(item_id, rec["bridge"])
        top_urn = ent_urn(item_id, rec["top"])
        w({"kind": "relation", "subject": base_urn,
           "relation": REL_OF[rec["t1"]], "object": bridge_urn}, prov)
        w({"kind": "relation", "subject": bridge_urn,
           "relation": REL_OF[rec["t2"]], "object": top_urn}, prov)
        # question path: fallback template for EVERY item (matches 958/958 of
        # the prior corpus; generator text_query preserved unused in provenance)
        question = "How is %s related to %s?" % (rec["query"][0], rec["query"][1])
        item = {
            "item_id": item_id, "stratum": "covered", "partition": partition,
            "context": [rec["story"]], "question": question,
            "gold_entity": None, "gold_surface": rec["target"],
            "gold_relation": rec["target"],
            "hop1": {"op": "unique", "rel": REL_OF[rec["t1"]],
                     "direction": "forward", "subject": base_urn},
            "hop1_bridge": bridge_urn,
            "hop2_rel_surface": rec["target"],
            "lexicon": lex,
            "provenance": {"config": rec["cfg"], "file": rec["file"],
                           "csv_row_id": rec["id"], "task_name": rec["task_name"],
                           "task_split": rec["task_split"],
                           "story_sha256": sha256_bytes(rec["story"].encode()),
                           "f_comb": rec["f_comb"], "edge_types": rec["edge_types"],
                           "story_edges": [list(e) for e in rec["story_edges"]],
                           "query_edge": list(rec["query_edge"]),
                           "genders": rec["genders_raw"],
                           "proof_state": rec["proof_state"], "target": rec["target"],
                           "text_query_generated_unused": rec["text_query"]},
        }
        return item

    items_a = [emit_covered(rec, "clutrr-r3a%04d" % (i + 1), "A")
               for i, rec in enumerate(part_a)]
    items_b = [emit_covered(rec, "clutrr-r3b%04d" % (i + 1), "B")
               for i, rec in enumerate(part_b)]
    all_items = items_a + items_b

    # ------------------------------------------------------------------ S9
    axioms = []
    for n in sorted(os.listdir(SRC_AXIOMS)):
        if n.endswith(".json"):
            axioms.append(("nsk1-clutrr-r3/axioms/%s" % n,
                           json.load(open(os.path.join(SRC_AXIOMS, n)))))
    engine = Engine(axioms, world)

    # S9.1 engine hop-1 resolution + S9.2 rule equivalence (VERBATIM checks)
    fail1 = fail2 = 0
    for it in all_items:
        res = engine.query(dict(it["hop1"]))
        if not (res.get("status") == "answer" and res.get("value") == it["hop1_bridge"]):
            fail1 += 1
        others = [u for u in it["lexicon"]
                  if u not in (it["hop1"]["subject"], it["hop1_bridge"])]
        endpoints = [it["hop1"]["subject"]] + others
        resolved = []
        for e in endpoints:
            for rel in (REL_MOTHER, REL_FATHER):
                rr = engine.query({"op": "unique", "rel": rel,
                                   "direction": "forward", "subject": e})
                if rr.get("status") == "answer":
                    resolved.append((e, rel, rr.get("value")))
        if not (len(resolved) == 1
                and resolved[0][0] == it["hop1"]["subject"]
                and resolved[0][1] == it["hop1"]["rel"]
                and resolved[0][2] == it["hop1_bridge"]):
            fail2 += 1
    if fail1:
        raise RuntimeError("ERR_S9_1_ENGINE_RESOLUTION: %d items" % fail1)
    if fail2:
        raise RuntimeError("ERR_S9_2_RULE_EQUIVALENCE: %d items" % fail2)

    # S9.3 (r3 form): 3-name pairwise distinct + donor pair construction
    # (D_top/D_bridge differ ONLY in the answer-slot name; design §6.4 step 1;
    # mirrors poc/modal/modal_nsk1_g2.py _build_specs_bprime2 asserts)
    fail3 = 0
    for it in all_items:
        lexs = list(it["lexicon"].values())
        if not (len(it["lexicon"]) == 3 and len({s.lower() for s in lexs}) == 3):
            raise RuntimeError("ERR_S9_3_NAMES: item %s not 3-name pairwise-distinct"
                               % it["item_id"])
        rs = REL_SURFACE[it["hop1"]["rel"]]
        subj = it["lexicon"][it["hop1"]["subject"]]
        bridge = it["lexicon"][it["hop1_bridge"]]
        top_urns = [u for u in it["lexicon"]
                    if u not in (it["hop1"]["subject"], it["hop1_bridge"])]
        top = it["lexicon"][top_urns[0]]
        prefix = "Note: the %s of %s is " % (rs, subj)
        d_top, d_bridge = prefix + top + ".", prefix + bridge + "."
        if not (d_top[:len(prefix)] == d_bridge[:len(prefix)]
                and d_top[-1] == d_bridge[-1] == "."
                and d_top != d_bridge):
            fail3 += 1
    if fail3:
        raise RuntimeError("ERR_S9_3_DONOR_PAIR: %d items" % fail3)

    # S9.4 gold-not-in-D_bridge (token-exact; VERBATIM check)
    fail4 = 0
    for it in all_items:
        rel_surf = REL_SURFACE[it["hop1"]["rel"]]
        subj = it["lexicon"][it["hop1"]["subject"]]
        obj = it["lexicon"][it["hop1_bridge"]]
        fb = "Note: the %s of %s is %s." % (rel_surf, subj, obj)
        toks = re.findall(r"[a-zA-Z][a-zA-Z-]*", fb.lower())
        if it["gold_surface"].lower() in toks:
            fail4 += 1
    if fail4:
        raise RuntimeError("ERR_S9_4_GOLD_IN_DBRIDGE: %d items" % fail4)

    # S9.6 (r3): disjointness asserts — fresh vs prior, and A vs B
    fresh_shas = [it["provenance"]["story_sha256"] for it in all_items]
    if set(fresh_shas) & prior_shas:
        raise RuntimeError("ERR_S9_6_PRIOR_OVERLAP")
    if len(set(fresh_shas)) != len(fresh_shas):
        raise RuntimeError("ERR_S9_6_INTERNAL_DUP")
    if {it["item_id"] for it in items_a} & {it["item_id"] for it in items_b}:
        raise RuntimeError("ERR_S9_6_PARTITION_OVERLAP")

    # S9.5 report-only: story-gold token contamination
    contam = 0
    for it in all_items:
        toks = set(re.findall(r"[a-z][a-z-]*", it["context"][0].lower()))
        if it["gold_surface"].lower() in toks:
            contam += 1

    # ------------------------------------------------------------------ write
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(os.path.join(OUT, "axioms"), exist_ok=True)
    for n in sorted(os.listdir(SRC_AXIOMS)):
        if n.endswith(".json"):
            shutil.copyfile(os.path.join(SRC_AXIOMS, n), os.path.join(OUT, "axioms", n))
    with open(os.path.join(OUT, "world.jsonl"), "w") as f:
        for rec in world:
            f.write(json.dumps(rec, sort_keys=True) + "\n")
    with open(os.path.join(OUT, "items.jsonl"), "w") as f:
        for it in all_items:
            f.write(json.dumps(it, sort_keys=True) + "\n")
    with open(os.path.join(OUT, "lexicon.json"), "w") as f:
        json.dump({"entities": {},
                   "relations_answer_vocab": rel_words,
                   "relations": {"mother": REL_MOTHER, "father": REL_FATHER},
                   "name_matching": ("per-item: each item carries a closed name "
                                     "lexicon (the read-channel match set); answer "
                                     "scoring is EXACT match over the closed "
                                     "relation vocabulary — no cosine (X3).")},
                  f, indent=1, sort_keys=True)
        f.write("\n")

    with open(os.path.join(OUT, "LICENSE-NOTICE"), "w") as f:
        f.write(
            "CLUTRR-derived evaluation slice (data/nsk1-clutrr-r3)\n"
            "=====================================================\n\n"
            "Source: generated with the pinned CLUTRR generator\n"
            "(github.com/facebookresearch/clutrr @ %s),\n"
            "seed %d, synthetic templating (see manifest deviation D-1).\n"
            "CLUTRR: Koustuv Sinha, Shagun Sodhani, Jin Dong, Joelle Pineau,\n"
            "William L. Hamilton. \"CLUTRR: A Diagnostic Benchmark for Inductive\n"
            "Reasoning from Text.\" EMNLP 2019. arXiv:1908.06177.\n\n"
            "Licence: the CLUTRR repository and dataset are released under\n"
            "CC-BY-NC-4.0 (Creative Commons Attribution-NonCommercial 4.0\n"
            "International); generated derivatives carry the same terms.\n"
            "https://creativecommons.org/licenses/by-nc/4.0/\n\n"
            "NON-COMMERCIAL USE ONLY — LICENCE QUARANTINE (S11 discipline):\n"
            "this directory is EVAL-SIDE ONLY. Nothing here enters kernel\n"
            "concepts, explications, molecules, or axiom content; the kernel\n"
            "artifact stays licence-clean. Do not train on, redistribute\n"
            "commercially, or fold these bytes into any released model or\n"
            "kernel artifact.\n" % (GENERATOR_COMMIT, GEN_SEED))

    n_a, n_b = len(items_a), len(items_b)
    gate = ("FULL-POWER (n>=300/cell)" if min(n_a, n_b) >= N_TARGET else
            ("REDUCED (175<=n<300): power must be redone at achieved n BEFORE freeze"
             if min(n_a, n_b) >= N_FLOOR else
             "DO-NOT-FREEZE (n<175/cell): escalate to maintainer"))
    manifest = {
        "corpus": "nsk1-clutrr-r3",
        "epistemic_status": ("MEASURED (provenance only) — every count below is a "
                             "pure function of the pinned generator commit + seeds "
                             "%d/%d under PYTHONHASHSEED=0; no experimental outcome "
                             "is recorded here." % (GEN_SEED, SPLIT_SEED)),
        "built_by": "poc/nsk1/build_clutrr_r3_corpus.py (runner role; nsk1-r3 §6.4 step 1)",
        "builder_sha256": sha256_bytes(open(__file__, "rb").read()),
        "prior_recipe_carried_from": {
            "builder": "poc/nsk1/build_clutrr_corpus.py",
            "builder_sha256": "b82993cec1322a0040ed00266a36f18a1d9b90b753e71e0826a038e46362db77",
            "carried": "S2 parse, S3 orientation self-check, S4 covered predicate, "
                       "S6 story-byte dedup, S9.1/S9.2/S9.4 asserts, item/world schema",
        },
        "seeds": {"generation": GEN_SEED, "partition_split": SPLIT_SEED},
        "derangement_seed_families_declared": {
            "A": [20260720, 20260721, 20260722], "B": [20260723, 20260724, 20260725],
            "note": "run-time seeds declared in registry/experiments/nsk1-r3.json; "
                    "not used at build"},
        "source": {
            "generator_repo": "https://github.com/facebookresearch/clutrr",
            "generator_commit": GENERATOR_COMMIT,
            "generation_invocation": None,  # filled below
            "dependency_versions": dep_versions,
            "relations_store_yaml_sha256": sha256_bytes(relstore_bytes),
            "relation_vocabulary_verbatim": rel_words,
        },
        "deviation_disclosures": {
            "D-1_synthetic_templating": (
                "The design (ASM-2357) stipulates generator regeneration yields "
                "'distributionally identical' fresh items. The AMT paraphrase "
                "templates (cleaned_placeholders.zip, sha256 pinned in the "
                "generator's main.py) are NO LONGER OBTAINABLE: canonical URL "
                "404s, no Wayback snapshot, no public mirror found (2026-07-14). "
                "This build uses the pinned generator's SYNTHETIC templating "
                "branch (use_mturk_template=False; combination_length=1 forced "
                "by that branch): chain structure/genders/proof_state/query are "
                "from the identical pinned code, but story surfaces are the "
                "generator's built-in per-relation phrasings — terser and less "
                "varied than the AMT-paraphrase surfaces B'/B\"/Stage-1 measured. "
                "REQUIRES designer adjudication BEFORE prereg-freeze."),
            "D-2_question_fallback_forced": (
                "All items use the fallback question template 'How is [A] "
                "related to [B]?' (released query order) to match 958/958 of "
                "the prior corpus (whose text_query was empty); the generator's "
                "synthetic text_query is preserved unused in provenance."),
            "D-3_csv_row_id_is_generation_index": (
                "The generator's per-puzzle uuid4 id is process-random (not "
                "seed-derived); provenance csv_row_id is the deterministic "
                "generation row index genrow-NNNNNN instead, keeping corpus "
                "bytes reproducible."),
        },
        "orientation_S3": {
            "population_clean_2edge_upedge_rows": len(rows2_for_s3),
            "scores": scores,
            "counts": {k: {"agree": v[0], "n": v[1]} for k, v in counts.items()},
            "determined_convention": "C1/Q1",
            "gender_G_vs_2nd_edge_disagreements": gmis,
        },
        "counts": {
            "generated_rows": len(recs_all),
            "parse_drops": drop_parse,
            "covered_candidates": len(covered_cands),
            "covered_pool_deduped": len(covered),
            "covered_pool_dedup_collisions": dup_cov,
            "prior_overlap_dropped": overlap_dropped,
            "fresh_pool": pool,
            "n_partition_A": n_a,
            "n_partition_B": n_b,
            "remainder_unused": pool - n_a - n_b,
            "world_records": len(world),
        },
        "drops": {
            "f_comb_disagreement": drop_fcomb,
            "duplicate_names_in_item": drop_dup_in_item,
            "missing_or_inconsistent_gender": drop_gender,
            "class_records_skipped_missing_gender": skipped_class_missing_gender[0],
        },
        "count_gate_6_3": {
            "n_target_per_cell": N_TARGET,
            "non_freeze_floor_per_cell": N_FLOOR,
            "n_A": n_a, "n_B": n_b,
            "branch": gate,
        },
        "build_assertions_S9": {
            "s9_1_engine_resolution": "PASS (100%%, %d items)" % len(all_items),
            "s9_2_rule_equivalence": "PASS (exactly one licensed unique lookup / item)",
            "s9_3_names_and_donor_pair": "PASS (3-name distinct; D_top/D_bridge "
                                         "differ only in the answer-slot name)",
            "s9_4_gold_not_in_dbridge": "PASS (no gold token in any D_bridge donor)",
            "s9_5_story_gold_token_contamination_covered": contam,
            "s9_6_disjointness": "PASS (fresh∩prior=∅ vs all 1058 prior story shas; "
                                 "A∩B=∅; no internal dups)",
        },
        "license": {"spdx": "CC-BY-NC-4.0",
                    "citation": "Sinha et al., EMNLP 2019, arXiv:1908.06177",
                    "eval_side_only_S11": True,
                    "quarantine_notice": "LICENSE-NOTICE"},
    }
    manifest["source"]["generation_invocation"] = invocation
    with open(os.path.join(OUT, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1, sort_keys=True)
        f.write("\n")

    print("nsk1-clutrr-r3 built:")
    print("  generated rows          : %d" % len(recs_all))
    print("  covered candidates      : %d" % len(covered_cands))
    print("  covered pool (deduped)  : %d  (dedup collisions %d)" % (len(covered), dup_cov))
    print("  prior-overlap dropped   : %d" % overlap_dropped)
    print("  fresh pool              : %d" % pool)
    print("  partition A / B         : %d / %d  (remainder unused %d)"
          % (n_a, n_b, pool - n_a - n_b))
    print("  S3 orientation scores   : %s" % scores)
    print("  S9 asserts              : ALL PASS (S9.5 contamination %d/%d)"
          % (contam, len(all_items)))
    print("  COUNT GATE (§6.3)       : %s" % gate)
    return 0


if __name__ == "__main__":
    sys.exit(main())
